### ISSUE TITLE
Usage Question

### ISSUE THREAD

**Issue by kerrtravers** [towerofnix/blog#26]
If I was to use this blog engine, where would you prefer the credit to be and what exactly would you like it to say?

**Comment by towerofnix** [comment]
You could probably put credits in the about page, which is generated from the file `/pages/about.md`.

(Sorry this is not really usable for the general public -- a lot of things are hard-coded!! I recommend you check out the publish branch to see [my publish script](https://github.com/towerofnix/blog/blob/publish/publish.sh). You'll definitely want to enter your own domain and not towerofnix.github.io in that or else *nothing* will work.)

**Comment by kerrtravers** [comment]
That's great, thanks!
